name: CI/CD Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Docker Containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

      - name: Build and push Docker image
        run: |
          docker build -f docker/images/Dockerfile.prod -t ${{ secrets.DOCKER_USER }}/mantecao-hub:latest .
          docker push ${{ secrets.DOCKER_USER }}/mantecao-hub:latest

      - name: Create .env file
        run: |
          echo "FLASK_APP_NAME=${{ secrets.FLASK_APP_NAME }}" > .env
          echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          echo "MARIADB_HOSTNAME=${{ secrets.MARIADB_HOSTNAME }}" >> .env
          echo "MARIADB_PORT=${{ secrets.MARIADB_PORT }}" >> .env
          echo "MARIADB_DATABASE=${{ secrets.MARIADB_DATABASE }}" >> .env
          echo "MARIADB_USER=${{ secrets.MARIADB_USER }}" >> .env
          echo "MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD }}" >> .env
          echo "MARIADB_ROOT_PASSWORD=${{ secrets.MARIADB_ROOT_PASSWORD }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "WORKING_DIR=${{ secrets.WORKING_DIR }}" >> .env

      - name: Set up and deploy containers
        run: docker compose -f docker/docker-compose.prod.yml up -d