name: CI/CD Docker Build

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Docker Containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u ${{secrets.DOCKER_USER}} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349

      - name: Build and push Docker image
        run: |
          docker build -f docker/images/Dockerfile.prod -t mantecao-EGC/mantecao-hub:latest .
          docker push mantecao-EGC/mantecao-hub:latest

      - name: Set up and deploy containers
        run: docker compose -f docker/docker-compose.prod.yml up -d