name: Release CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'Merge') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: bump
        run: |
          # Extract the source branch name from merge commit message
          BRANCH_NAME=$(git log -1 --pretty=%s | sed -n 's/Merge pull request #[0-9]* from \(.*\)/\1/p')
          echo "Detected branch: $BRANCH_NAME"
          
          # Determine the version bump based on the branch name
          if [[ $BRANCH_NAME == Feat-* ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif [[ $BRANCH_NAME == Enhancement-* ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          elif [[ $BRANCH_NAME == Fix-* ]] || [[ $BRANCH_NAME == bug/* ]]; then
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/git @semantic-release/github

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUMP_LEVEL: ${{ steps.bump.outputs.bump }}
        run: |
          if [ ! -z "$BUMP_LEVEL" ]; then
            npx semantic-release --preset angular --release-rules '[{"type":"*","release":"${{ steps.bump.outputs.bump }}"}]'
          fi
